[package]
name = "edtui"
version = "0.3.3"
edition = "2021"
repository = "https://github.com/preiter93/edtui"
keywords = ["ratatui", "tui", "editor", "text", "vim"]
description = "A TUI based vim inspired editor"
authors = ["preiter <phil.reiter93@gmail.com>"]
license = "MIT"

[dependencies]
ratatui = "0.26"
jagged = { package = "edtui-jagged", version = "0.1.3" }
enum_dispatch = "0.3.12"
crossterm = "0.27"
arboard = { version = "3.3.0", optional = true }

[[example]]
name = "app"

[features]
default = ["arboard"]
arboard = ["dep:arboard"]
